projects:
  dhprojectapi:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: vcoe5sjig5cvxh6lv57nslumbe
      endpoints:
        prod: >-
          https://klff44tfjjgone3i5ntenjxfv4.appsync-api.us-west-2.amazonaws.com/graphql
