import React, { Component } from "react";
import Amplify from 'aws-amplify';
import App from "./App.js"
import { Authenticator } from 'aws-amplify-react';
//import awsmobile from './aws-exports'; default file generated by amplify
//import { awsConfig, signUpConfig } from "./awsConfig";
import awsmobile from "./aws-exports.js";

Amplify.configure(awsmobile);

class AppWithAuth extends Component {
  render(){
    return (
      <div>
        <Authenticator>
          <App />
        </Authenticator>
      </div>
    );
  }
}

export default AppWithAuth;